
services:
    postgres:
        image: postgres:12.3-alpine
        restart: always
        environment: 
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=admin
          - POSTGRES_DB=postgres
        ports:
          - '3000:5432'
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
          - ./sql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

