version: '3.8'
services:
  postgres:
    container_name: db-postgres
    image: postgres:12.3-alpine
    restart: always
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${PORT}:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./src:/docker-entrypoint-initdb.d/src
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
